version: "3.7"
services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/api
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - FLASK_ENV=${FLASK_ENV}
  db:
    container_name: db
    restart: always
    image: postgres:12.0-alpine
    env_file:
      - ./.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}


      
